### ISSUE TITLE
Freeze up when attempting to open a file.

### ISSUE THREAD

**Issue by Bigshooter** [khoih-prog/FS_Nano33BLE#9] opened 2023-01-17 19:20 UTC
### Describe the bug

FILE *file = fopen(path, "w");

Stops all execution on nano 3.3 ble.

### Steps to Reproduce

```
void Storage::WriteFile(const char * path, const char * message, size_t messageSize){
    bool isOpen = false;
    /* char fullPath[sizeof(MBED_FS_FILE_PREFIX) + sizeof(path)];
    strcpy(fullPath,MBED_FS_FILE_PREFIX);
    strcat(fullPath, path); */
    if(*_debug) _communication->Send("Writing file: ");
    if(*_debug) _communication->Send(path);

    FILE *file = fopen(path, "w");

    if (file)
    {
        isOpen = true;
        if(*_debug) _communication->Send(" => Open OK");
    }
    else
    {
        if(*_debug) _communication->Send(" => Open Failed");
    }

    if(isOpen){
        if (fwrite((uint8_t *) message, 1, messageSize, file))
        {
            if(*_debug) _communication->Send("* Writing OK");
        }
        else
        {
            if(*_debug) _communication->Send("* Writing failed");
        }

        fclose(file);
    }

}
```

### Expected behavior

the file should open or error out.

### Actual behavior

nothing happens, code stop executing

Please ensure to specify the following:

* Arduino IDE version (e.g. 1.8.19) or Platform.io version
Visual Studio Code
* `nRF52840 mbed` Core Version (e.g. Arduino mbed_nano core v3.4.1, Seeeduino mbed core v2.7.2)
BN: Arduino Nano 33 BLE
VID: 2341
PID: 805a
SN: C0FE91FA29BB3E26

Updated to Core 3.5.4

**Comment by khoih-prog** [comment] 2023-01-18 04:39
HI @Bigshooter 

Sorry I can't help you anything now as my only Nano-33-BLE was dead and I have no more interest in continue.

Did you try the unmodified examples and having the issue ? Also try the previous core versions to see if the real bug has been introduced in new cores

If still working, the problem is in your code.

I'm closing the issue now, unless you can prove the bug is in library.

Good Luck,

**Closed as completed by khoih-prog** 2023-01-18 04:39 UTC
